### ISSUE TITLE
Es restarts when applying charts with updated indexer version

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/KMS-generic-helm-charts#30]
If I upgrade the helm charts after updating the indexer image tag, the elasticsearch pods get recreated. Ideally, they should keep running to avoid downtime (the kms-generic pods don't seem to be affect, which makes me think it’s possible).

**Comment by gpelouze** [comment]
@skoulouzis do you know how to solve this?

**Comment by skoulouzis** [comment]
In general, if ES has somewhere Deployment.spec.strategy.   to Rolling Strategy or Recreate Strategy it will restart the pods. We may need to look at the values of ES to check if we can change this.

**Comment by skoulouzis** [comment]
Based on the values: https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml L481,L787,L1082... and some more 
we can set:
```yaml
master:
    updateStrategy:
        type: OnDelete
data:
    updateStrategy:
        type: OnDelete

```
Currently is set to RollingUpdate. I'm not sure what is the exact behavior with RollingUpdate
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies

**Comment by gpelouze** [comment]
Yes this works, thanks!
